version: '3'

services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo_db
    restart: always


  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./application:/application
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/todo_db
    entrypoint: /bin/sh -c "/application/script/wait-for-it.sh db:5432 -- uvicorn application.main:app --host=0.0.0.0 --reload --port=80"


