services:
  db:
    image: postgres:15
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - docker-elk
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo_db
    restart: always


  server:
    build:
      context: .
      dockerfile: Dockerfile
    x-develop:
      watch:
        - path: ./application
          action: sync
          target: /application
    networks:
      - docker-elk
    ports:
      - "80:80"
    volumes:
      - ./application:/application
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/todo_db
    entrypoint: /bin/sh -c "/application/script/wait-for-it.sh db:5432 -- /application/script/wait-for-it.sh elasticsearchhh:9200 -t 8 -- uvicorn application.main:app --host 0.0.0.0 --reload --port 80"
  
  elasticsearch:
    image: elasticsearch:8.12.0
    container_name: elasticsearch
    volumes:
      - ./elastic_data_storage:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.http.ssl.enabled=false
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=password
    user: "1000:1000"
    networks:
      - docker-elk
    ports:
      - 9200:9200

  kibana:
    image: kibana:8.12.0
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    networks:
      - docker-elk
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

networks:
  docker-elk:
    driver: bridge


volumes:
  postgres_data:  
